name: Docker Image CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag vfb-pipeline-updatetriplestore:${GITHUB_REF#refs/heads/}

      - name: Dockerize and Publish to Docker Hub
        uses: manusa/actions-publish-docker@v1.1.2
        with:
          name: virtualflybrain/vfb-pipeline-updatetriplestore
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
